"use server"

import { revalidatePath } from "next/cache"
import { z } from "zod"
import { createServerClient, createServiceClient } from "@/lib/supabase/server"
import { withCompliance } from "@/server/compliance"
import { stampPacket } from "@/server/legal/pdf/pdf-stamper"
import { fillDemoPetition } from "@/server/legal/utah-courts/forms/custody/demo-petition/fill"
import { getFormBySlug } from "@/server/legal/utah-courts/forms/registry"

const inputSchema = z.object({
  caseId: z.string().uuid(),
  formSlug: z.string().min(2),
})

export interface PrintFormResult {
  ok: boolean
  storagePath?: string
  signedUrl?: string
  errorCode?:
    | "auth"
    | "validation"
    | "case_not_found"
    | "form_not_found"
    | "no_response"
    | "generic"
  errorMessage?: string
}

export async function printFormAction(input: unknown): Promise<PrintFormResult> {
  const parsed = inputSchema.safeParse(input)
  if (!parsed.success) return { ok: false, errorCode: "validation" }

  const supabase = await createServerClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return { ok: false, errorCode: "auth" }

  const form = getFormBySlug(parsed.data.formSlug)
  if (!form) return { ok: false, errorCode: "form_not_found" }

  const { data: caseRow } = await supabase
    .from("cases")
    .select("id, client_id, case_number, display_name")
    .eq("id", parsed.data.caseId)
    .eq("client_id", user.id)
    .maybeSingle()
  if (!caseRow) return { ok: false, errorCode: "case_not_found" }

  return withCompliance(
    {
      action: "form_response.printed",
      resourceType: "form_responses",
      userId: user.id,
      metadata: { caseId: caseRow.id, formSlug: parsed.data.formSlug },
    },
    async (): Promise<PrintFormResult> => {
      const service = createServiceClient()
      const { data: response } = await service
        .from("form_responses")
        .select("id, responses, print_count")
        .eq("case_id", caseRow.id)
        .eq("form_slug", parsed.data.formSlug)
        .maybeSingle()
      if (!response) return { ok: false, errorCode: "no_response" }

      const values = (response.responses ?? {}) as Record<string, unknown>

      // Por ahora sólo el demo petition tiene fill function. Cuando se agreguen
      // más, mover a un dispatcher en `forms/_shared/dispatch-fill.ts`.
      let pdfBytes: Uint8Array
      if (form.slug === "utah-custody-demo-petition") {
        pdfBytes = await fillDemoPetition(
          values,
          `${caseRow.case_number} · ${caseRow.display_name}`,
        )
      } else {
        return { ok: false, errorCode: "generic", errorMessage: "fill no implementado" }
      }

      // Aplicar stamp UPL/disclaimers
      const stampedBytes = await stampPacket(pdfBytes, {
        footerEs: "Generado por USA Latino Prime Utah · NO es asesoría legal · Sandbox Phase 2",
        footerEn: "Generated by USA Latino Prime Utah · NOT legal advice · Sandbox Phase 2",
        headerCaseNumber: caseRow.case_number,
      })

      const filename = `${form.slug}-${Date.now()}.pdf`
      const storagePath = `${user.id}/${caseRow.id}/forms/${filename}`
      const { error: upErr } = await service.storage
        .from("generated-pdfs")
        .upload(storagePath, stampedBytes, {
          contentType: "application/pdf",
          upsert: false,
        })
      if (upErr) {
        return { ok: false, errorCode: "generic", errorMessage: upErr.message }
      }

      const { data: signed } = await service.storage
        .from("generated-pdfs")
        .createSignedUrl(storagePath, 60)

      await service
        .from("form_responses")
        .update({
          last_printed_at: new Date().toISOString(),
          print_count: (response.print_count ?? 0) + 1,
          status: "printed",
        })
        .eq("id", response.id)

      revalidatePath(`/[locale]/cases/${caseRow.id}/forms`, "page")
      const result: PrintFormResult = { ok: true, storagePath }
      if (signed?.signedUrl) result.signedUrl = signed.signedUrl
      return result
    },
  )
}
